imageNameFormat: "ghcr.io/edera-dev/[image]:[tag]"
architectures:
- x86_64
- aarch64
flavors:
- name: zone
- name: zone-openpax
  constraints:
    series:
    - '6.10'
    - '6.11'
- name: host
versions:
- current: true
- lower: '5.15'
patches:
- patch: hvc-xen-idm-support-1.patch
  series:
  - '5.10'
  upper: 5.10.210
- patch: hvc-xen-idm-support-2.patch
  series:
  - '5.10'
  lower: '5.10.211'
- patch: 0001-Revert-ALSA-memalloc-Workaround-for-Xen-PV.patch
  series:
  - '6.6'
  - '6.7'
  - '6.8'
  - '6.9'
  - '6.10'
  - '6.11'
- patch: openpax-6.10-20240913112548.patch
  series: '6.10'
  flavors:
  - zone-openpax
- patch: openpax-6.11.2-20241009165538.patch
  series: '6.11'
  flavors:
  - zone-openpax
- patch: 0001-x86-topology-Tolerate-lack-of-APIC-when-booting-as-X_01.patch
  lower: '6.10'
  upper: '6.12.4'
- patch: 0001-x86-topology-Tolerate-lack-of-APIC-when-booting-as-X_02.patch
  lower: '6.12.5'
- patches:
  - 9pfs-xen-hotplug-1.patch
  - 9pfs-xen-hotplug-2.patch
  any:
  - series: '6.6'
    upper: '6.6.63'
  - series: '6.12'
    upper: '6.12.1'
- patch: 0001-x86-static-call-Remove-early_boot_irqs_disabled-check.patch
  any:
  - series: '5.15'
    lower: '5.15.175'
  - series: '6.1'
    lower: '6.1.121'
  - series: '6.6'
    lower: '6.6.67'
  - lower: '6.12.6'
images:
- target: kernelsrc
  name: kernel-src
  publish: false
  passBuildArgs: false
- target: buildenv
  name: kernel-buildenv
  publish: false
  passBuildArgs: false
  version: local
  tags:
  - local
- target: kernel
  name: "[flavor]-kernel"
  format: kernel
- target: sdk
  name: "[flavor]-kernel-sdk"
  format: kernel.sdk
runners:
- name: edera-large
  flavors:
  - host
- name: ubuntu-latest
