name: build
on:
  push:
    branches:
    - main
jobs:
  build:
    name: "build ${{ matrix.arch }} ${{ matrix.version.version }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version:
        - config: stable
          version: "stable"
        - config: custom-release
          version: "6.7"
        arch:
        - x86_64
        - aarch64
    env:
      TARGET_ARCH: "${{ matrix.arch }}"
      KERNEL_VERSION: "${{ matrix.version.version }}"
      KERNEL_VERSION_CONFIG: "${{ matrix.version.config }}"
    steps:
    - name: checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: install dependencies
      run: ./hack/ci/install-linux-deps.sh
    - name: build kernel
      run: ./hack/build.sh
      env:
        KERNEL_BUILD_JOBS: "5"
    - name: identify kernel
      id: identify
      run: echo "version=$(./hack/identify-kernel.sh target/kernel)" >> "${GITHUB_OUTPUT}"
    - name: write metadata
      run: |
        echo "KERNEL_ARCH=${{ matrix.arch }}" > target/metadata
        echo "KERNEL_VERSION=${{ steps.identify.outputs.version }}" >> target/metadata
    - name: upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: "kernel-${{ matrix.arch }}-${{ steps.identify.outputs.version }}"
        path: "target/*"
        compression-level: 0
  bundle:
    name: bundle
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: bundle artifacts
      uses: actions/upload-artifact/merge@v4
      with:
        name: kernels
        separate-directories: true
        compression-level: 0
