name: kernel
on:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
        - x86_64
        - aarch64
        flavor:
        - latest
    env:
      TARGET_ARCH: "${{ matrix.arch }}"
    name: kernel build ${{ matrix.arch }} ${{ matrix.flavor }}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: dtolnay/rust-toolchain@stable
    - run: ./hack/ci/install-linux-deps.sh
    - run: ./build.sh "${{ matrix.flavor }}"
      env:
        KRATA_KERNEL_BUILD_JOBS: "5"
